---
- name: Create CKB Main Configuration File
  template:
    src: ckb.toml.j2
    dest: "{{ ckb.workspace }}/ckb.toml"
    group: ckb
    owner: ckb
    mode: 0666
  notify: Restart CKB

- name: Create Chain Spec
  template:
    src: "{{ ckb.spec.file }}"
    dest: "{{ ckb.workspace }}/spec.toml"
    group: ckb
    owner: ckb
    mode: 0666
  notify: Restart CKB
  when:
    - ckb.spec.file is defined and ckb.spec.file != ''

- name: Create CKB Network Secret Key
  copy:
    src: "{{ ckb.network_secret_key }}"
    dest: "{{ ckb.data_dir }}/network/secret_key"
    group: ckb
    owner: ckb
    mode: 0400
  notify: Restart CKB
  when:
    - ckb.network_secret_key is defined

- name: Create CKB Systemd Configuration File
  become: true
  template:
    src: ckb.service.j2
    dest: /etc/systemd/system/{{ ckb.service }}.service
  notify: Restart CKB
