---
- name: Install CKB From Local Source
  block:
    - name: Upload CKB Tarball From Local
      copy:
        force: true
        src: "{{ ckb_local_source }}"
        dest: "{{ ckb_download_tmp_dir }}/{{ ckb_local_source | basename }}"
        group: ckb
        owner: ckb
    - name: Unarchive CKB Tarball
      become: true
      unarchive:
        remote_src: true
        src: "{{ ckb_download_tmp_dir }}/{{ ckb_local_source | basename }}"
        dest: "{{ ckb_workspace }}"
        mode: 0777
        extra_opts:
          - --wildcards
          - '*ckb'             # unarchive "ckb" only
          - --transform
          - 's/.*\/ckb$/ckb/'  # transform "xxx/ckb" => "ckb"
      when: not ckb_local_source.endswith(".7z")
    - name: Unarchive CKB 7z-Tarball
      become: true
      shell: |
        7z e -y -o'{{ ckb_workspace }}' '{{ ckb_download_tmp_dir }}/{{ ckb_local_source | basename }}' '*/ckb'
      when: ckb_local_source.endswith(".7z")
  when:
    - ckb_local_source is defined and ckb_local_source != ''

- name: Install CKB From Remote Source
  block:
    - name: Download CKB Tarball From URL
      environment:
        ckb_data_download_url: "{{ ckb_download_url }}"
      shell:
        cmd: |
          if [ ! -f {{ ckb_download_tmp_dir }}/$(basename {{ ckb_download_url }}) ]; then
            wget -P {{ ckb_download_tmp_dir }}/ {{ ckb_download_url }}
          fi
    - name: Unarchive CKB Tarball
      become: true
      unarchive:
        remote_src: true
        src: "{{ ckb_download_tmp_dir }}/{{ ckb_download_url | basename }}"
        dest: "{{ ckb_workspace }}"
        mode: 0777
        extra_opts:
          - --wildcards
          - '*ckb'             # unarchive "ckb" only
          - --transform
          - 's/.*\/ckb$/ckb/'  # transform "xxx/ckb" => "ckb"
      when: not ckb_download_url.endswith(".7z")
    - name: Unarchive CKB 7z-Tarball
      become: true
      shell: |
        7z e -y -o'{{ ckb_workspace }}' '{{ ckb_download_tmp_dir }}/{{ ckb_download_url | basename }}' '*/ckb'
      when: ckb_download_url.endswith(".7z")
  when:
    - (ckb_local_source is not defined or ckb_local_source == '') and ckb_download_url is defined
